project_name: chkRedis
env:
  - CGO_ENABLED=0
builds:
  - binary: chkRedis
    id: chkRedis
    main: ./
    ldflags:
      - -X main.Version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
release:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  header: |
    ## {{ .Version }} ({{ .Date }})
    New {{ .Version }} release!
  footer: |
    ## Release Notes
    Please read the [RELEASE_NOTES](https://github.com/allaman/chkRedis/blob/master/RELEASE-NOTES.md) which contain among other things important information for who is upgrading from previous releases.
    ## Thanks!
