version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  vet:
    desc: Run go vet
    cmds:
      - go vet

  build:
    desc: Build App
    cmds:
      - go build

  upgrade-deps:
    desc: Upgrade all dependencies
    cmds:
      - go get -u ./...

  test:
    desc: Start Redis and run chkRedis
    deps:
      - build
    cmds:
      - defer: rm chkRedis && docker stop chkRedis-redis
      - docker run --rm -d -p 6379:6379 --name chkRedis-redis redis redis-server --requirepass "password"
      - sleep 3
      - ./chkRedis -a localhost:6379 -p password
