---
version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  vet:
    desc: Run go vet
    cmds:
      - go vet

  build:
    desc: Build App
    cmds:
      - go build

  upgrade-deps:
    desc: Upgrade all dependencies
    cmds:
      - go get -u ./...

  test:
    desc: Run tests
    summary: Run tests via testcontainers (requires Docker)
    deps:
      - build
    cmds:
      - go test -v
